baseURL = "https://ajguerrer.github.io/"
languageCode = "en-us"
title = "Notebook"
theme = "hugo-theme-learn"

# For search functionality
[outputs]
	home = [ "HTML", "RSS", "JSON"]

# Apply custom gruvbox css to theme
[params]
	themeVariant = "gruvbox"