baseURL = "https://ajguerrer.github.io/"
languageCode = "en-us"
title = "Notebook"
theme = "hugo-theme-learn"
# Hack to prevent Hugo's Chroma highlighter from interfering with highlight.js
pygmentsUseClasses = true

# For search functionality
[outputs]
	home = [ "HTML", "RSS", "JSON"]

# Apply custom gruvbox css to theme
[params]
	themeVariant = "gruvbox"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true